nameOverride: ""
fullnameOverride: ""

service:
  port: 8080

route:
  enabled: true
  host:
  localName: 
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

admin:
  username: admin
  password: ""
  secret: ""

database:
  vendor: postgres
  host: keycloak-db
  secret: keycloak-db

ingress:
  enabled: false

argocd:
  enabled: true
  syncwave: "-1"
  adminSecret:
    syncwave: "-2"

keycloak:
  admin:
    username: admin
    password: admin