global:
  kafka:
    name: &kafka kafka
    namespace: &kafkanamespace kafka
    kafka-cluster: &kafkacluster
      bootstrapServer: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
      securityProtocol: SASL_PLAINTEXT
      saslMechanism: SCRAM-SHA-512
      clientId: globex
      clientSecret: globex

amqstreams:
  enabled: true
  applicationName: amqstreams
  applicationNamespace: openshift-gitops
  destinationNamespace: kafka
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: amq-streams
    helm:
      values:
        kafka:
          enabled: true
        console:
          enabled: true

        kafka-broker:
          namespace: *kafkanamespace
          nameOverride: *kafka
          kafka:
            controller:
              enabled: true
            listener:
              external:
                tls:
                  secret:
                    value:
                      crt: 
                      key: 
          authentication:
            clientId: admin
            clientSecret: adminpassword
            securityProtocol: SASL_PLAINTEXT
            saslMechanism: SCRAM-SHA-512
        amq-streams-console:
          namespace: *kafkanamespace
          subdomain: 
          kafka:
            name: *kafka
            namespace: *kafkanamespace
            authentication:
              securityProtocol: SASL_SSL
              saslMechanism: SCRAM-SHA-512
            authorization: simple
        kafka-topics:
          kafka:
            namespace: *kafkanamespace
            cluster: *kafka
  argocd:
    enabled: true
    syncwave: "1"

keycloak:
  enabled: true
  applicationName: keycloak
  applicationNamespace: openshift-gitops
  destinationNamespace: keycloak
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: keycloak
    helm:
      values:
        keycloak:
          nameOverride: keycloak
          route:
            host:
          ingress:
            enabled: false
  argocd:
    enabled: true
    syncwave: "1"

globex:
  enabled: true
  applicationName: globex
  applicationNamespace: openshift-gitops
  destinationNamespace: globex
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: globex
    helm:
      values:
        kafka-broker:
          namespace: *kafkanamespace
          nameOverride: *kafka

        kafka-topics:
          kafka:
            namespace: *kafkanamespace
            cluster: *kafka
        globex-db:
          pgsql:
            user: globex
            password: globex
            database: globex
            adminPassword: adminpassword

        keycloak-realmimport-globex:
          namespace: keycloak
          keycloak:
            name: keycloak
          realm:
            name: globex
          client:
            gateway:
              name: globex-web-gateway

        globex-web:
          sso:
            authServer:
            realm: globex
            client: globex-web-gateway
          subdomain:
          globexAgent:
            url: http://globex-complaint-agent.globex-complaint-agent.svc.cluster.local:8080

        activity-tracking:
          kafka:
            <<: *kafkacluster

        recommendation-engine:
          kafka:
            <<: *kafkacluster

  argocd:
    enabled: true
    syncwave: "3"

noobaa:
  enabled: false
  applicationName: noobaa
  applicationNamespace: openshift-gitops
  destinationNamespace: openshift-storage
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: noobaa
    helm:
      values:
        noobaa:
          nameOverride: noobaa

  argocd:
    enabled: true
    syncwave: "1"

vault:
  enabled: false
  applicationName: vault
  applicationNamespace: openshift-gitops
  destinationNamespace: vault
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: vault
    helm:
      values:
        nameOverride: vault
        kubernetes:
          apiserver:
        vault:
          auth:
            namespace: default

  argocd:
    enabled: true
    syncwave: "1"

quay:
  enabled: false
  applicationName: quay
  applicationNamespace: openshift-gitops
  destinationNamespace: quay
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: quay
    helm:
      values:
        quay-registry:
          quay:
            host: 
            adminUser: admin
            adminUserPassword: 
            organizations:
          noobaa:
            name: noobaa
            namespace: openshift-storage

  argocd:
    enabled: true
    syncwave: "2"

gitlab:
  enabled: true
  applicationName: gitlab
  applicationNamespace: openshift-gitops
  destinationNamespace: gitlab
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: gitlab
    helm:
      values:
        gitlab:
          rootPassword:
          users:
            password:
          host:
          smtp:
            host:
          ssh:
            host:
  argocd:
    enabled: true
    syncwave: "2"

pipelines:
  enabled: true
  applicationName: openshift-pipelines
  applicationNamespace: openshift-gitops
  destinationNamespace: openshift-operators
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: openshift-pipelines

  argocd:
    enabled: true
    syncwave: "1"

globexStoreMcpBuild:
  enabled: true
  applicationName: globex-store-mcp-build
  applicationNamespace: openshift-gitops
  destinationNamespace: globex-store-mcp-build
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: globex-store-mcp-build
    helm:
      values:
        gitlab:
          namespace: gitlab
          tokenSecret: root-user-personal-token
          host:
          group: globex
          repo: globex-store-mcp
          branch: main
          webhookSecret:
        cluster:
          subdomain:
        image:
          registry: OpenShift
          organization: ""
          host: image-registry.openshift-image-registry.svc:5000
          name: globex-store-mcp
          tag: latest
        resync:
          namespace: globex-store-mcp
          label: globex-store-mcp
  argocd:
    enabled: true
    syncwave: "3"

globexStoreMcp:
  enabled: true
  applicationName: globex-store-mcp
  applicationNamespace: openshift-gitops
  destinationNamespace: globex-store-mcp
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: globex-store-mcp
    helm:
      values:
        route:
          host:
        image:
          repository: image-registry.openshift-image-registry.svc:5000/globex-store-mcp-build/globex-store-mcp
          tag: latest
          pullPolicy: Always
        roleBinding:
          imagePull:
            namespace: globex-store-mcp-build
  argocd:
    enabled: true
    syncwave: "4"

globexComplaintsBuild:
  enabled: true
  applicationName: globex-complaints-build
  applicationNamespace: openshift-gitops
  destinationNamespace: globex-complaints-build
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: globex-complaints-build
    helm:
      values:
        gitlab:
          namespace: gitlab
          tokenSecret: root-user-personal-token
          host:
          group: globex
          repo: globex-complaints
          branch: main
          webhookSecret:
        cluster:
          subdomain:
        image:
          registry: OpenShift
          organization: ""
          host: image-registry.openshift-image-registry.svc:5000
          name: globex-complaints
          tag: latest
        resync:
          namespace: globex-complaints
          label: globex-complaints
  argocd:
    enabled: true
    syncwave: "3"

globexComplaints:
  enabled: true
  applicationName: globex-complaints
  applicationNamespace: openshift-gitops
  destinationNamespace: globex-complaints
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: globex-complaints
    helm:
      values:
        route:
          host:
        image:
          repository: image-registry.openshift-image-registry.svc:5000/globex-complaints-build/globex-complaints
          tag: latest
          pullPolicy: Always
        roleBinding:
          imagePull:
            namespace: globex-complaints-build
        globexDb:
          host: globex-db.globex.svc.cluster.local
          port: "5432"
          database: globex
          user: globex
          password: globex
  argocd:
    enabled: true
    syncwave: "4"

globexComplaintAgentBuild:
  enabled: true
  applicationName: globex-complaint-agent-build
  applicationNamespace: openshift-gitops
  destinationNamespace: globex-complaint-agent-build
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: globex-complaint-agent-build
    helm:
      values:
        gitlab:
          namespace: gitlab
          tokenSecret: root-user-personal-token
          host:
          group: globex
          repo: globex-complaint-agent
          branch: main
          webhookSecret:
        cluster:
          subdomain:
        image:
          registry: OpenShift
          organization: ""
          host: image-registry.openshift-image-registry.svc:5000
          name: globex-complaint-agent
          tag: latest
        resync:
          namespace: globex-complaint-agent
          label: globex-complaint-agent
  argocd:
    enabled: true
    syncwave: "3"

globexComplaintAgent:
  enabled: true
  applicationName: globex-complaint-agent
  applicationNamespace: openshift-gitops
  destinationNamespace: globex-complaint-agent
  source:
    repoUrl: https://{{ .Values.gitlab.source.helm.values.gitlab.host }}/globex/globex-complaint-agent-helm.git
    targetRevision: main
    path: .
    helm:
      values:
        route:
          host:
        image:
          repository: image-registry.openshift-image-registry.svc:5000/globex-complaint-agent-build/globex-complaint-agent
          tag: latest
          pullPolicy: Always
        roleBinding:
          imagePull:
            namespace: globex-complaint-agent-build
        oidc:
          authServerUrl:
          realm: globex
          clientId: globex-web-gateway
          clientSecret:
        cors:
          enabled: true
  argocd:
    enabled: true
    syncwave: "4"

zeroTrustWorkloadIdentityManager:
  enabled: true
  applicationName: zero-trust-workload-identity-manager
  applicationNamespace: openshift-gitops
  destinationNamespace: zero-trust-workload-identity-manager
  source:
    repoUrl: https://github.com/mcp-developers-workshop/install-helm.git
    targetRevision: main
    path: zero-trust-workload-identity-manager
    helm:
      values:
        trustDomain: globex.com
        clusterName: globex-cluster
        jwtIssuer:
  argocd:
    enabled: true
    syncwave: "1"
