{{- if and .Values.admin.password (not .Values.admin.secret) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "keycloak.adminSecretName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    {{- include "keycloak-admin.argocd-syncwave" . | nindent 4 }}
stringData:
  username: {{ .Values.admin.username | quote }}
  password: {{ .Values.admin.password | quote }}
type: kubernetes.io/basic-auth
{{- end }}
