gitlab:
  image: quay.io/redhat-gpte/gitlab:17.4.1
  email:
    address: "gitlab@example.com"
    displayName: "GitLab Admin"
    replyTo: "noreply@example.com"
  smtp:
    enabled: "false"
    domain: "example.com"
    host:
    port: "587"
    user: "gitlab"
    password: "gitlab"
  ssh:
    host:
    port: "22"
  rootPassword:
  host:
  https: "true"
  rootEmail: "root@example.com"
  keyBase:
    db: "0123456789"
    otp: "0123456789"
    secret: "0123456789"
  users:
    users:
      - id: developer
    password: 
  groups:
    - name: globex
      repo:
        - name: globex-store-mcp
          url: https://github.com/mcp-developers-workshop/globex-store-mcp.git
        - name: globex-complaints
          url: https://github.com/mcp-developers-workshop/globex-complaints.git
        - name: globex-complaint-agent
          url: https://github.com/mcp-developers-workshop/globex-complaint-agent.git
        - name: globex-complaint-agent-helm
          url: https://github.com/mcp-developers-workshop/globex-complaint-agent-helm.git
        - name: globex-complaints-orchestrate
          url: https://github.com/mcp-developers-workshop/globex-complaints-orchestrate.git
      users:
        - id: developer
      project:
        - name: globex-issues
          labels: []
  templates: []
postgresql:
  dbUser: gitlab
  dbPassword: passw0rd
  dbName: gitlab_production
