apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-config
  labels:
    {{- include "globex-issues-mcp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.job.gitlabConfig.argocd.syncwave }}"
